### ISSUE TITLE
No pairwise_distance file to import

### ISSUE THREAD

**Issue by nitschw** [yzhq97/cnn-registration#1]
I was wrong about before, so I deleted the comment.

I am curious however if this supports images of different dimensions or if the input image must always be a static size?

**Comment by inrainbws** [comment]
The input image can be of any size as along as the width and height are multiples of 32. The size of the input image can have two aspects of influence: (i) The receptive field of each descriptor would be different and may affect the performance. (ii) Larger input image requires more computation.

**Comment by Borda** [comment]
the `pairwise_distance` module is missing in `utils` package so it is impossible to import it...

**Comment by blutjens** [comment]
I think, going into `shape_context.py` and changing the import into `from utils.utils import pairwise_distance` might solve your issue.
 `
