### ISSUE TITLE
got unexpected results

### ISSUE THREAD

**Issue by engmubarak48** [yzhq97/cnn-registration#12]
Dear author, 

I have tried to use your CNN based image registration method but got unexpected results. Here I have attached the fixed, sensed, registered and cp images. please take a look at it and let me know if the results are supposed to be like that. Initially, I was expecting an unbent registered image which doesn't have those extra black pixels. 

Thanks. 
![fixed](https://user-images.githubusercontent.com/36045704/57920037-bcdac600-78a2-11e9-8640-5abbf293a6c7.jpg)
![moving](https://user-images.githubusercontent.com/36045704/57920038-bd735c80-78a2-11e9-83eb-183ff2212691.jpg)
![registered](https://user-images.githubusercontent.com/36045704/57920040-bd735c80-78a2-11e9-9d41-66d8d762e462.png)
![cb](https://user-images.githubusercontent.com/36045704/57920036-bcdac600-78a2-11e9-9445-5fad3c9fcbf2.png)

**Comment by inrainbws** [comment]
Sorry that it does not generalize well on your data. The algorithm is originally developed for remote sensing images.
