### ISSUE TITLE
Application for medical images

### ISSUE THREAD

**Issue by Borda** [yzhq97/cnn-registration#16]
Hello, I came across to this nice project and it seems quite powerful. Have you experienced to use it also for large histology images? Would you be interested in participating in [AHNIR challenge](https://anhir.grand-challenge.org/)?
You may also see other interesting methods from this domain https://github.com/Borda/BIRL/issues/2

**Comment by Borda** [comment]
@yzhq97 ^^ what is your opinion?

**Comment by inrainbws** [comment]
Hi, thanks for the oppurtunity! I do have some ideas of improving the current method. However, I am already occupied with other research projects and course work, so I will not participate in the challange. Thanks again!

**Comment by Borda** [comment]
Sure, and do you think that your method is suitable for such type and size of images?

**Comment by inrainbws** [comment]
I think it would work with some fine-tuning. However, I noticed that the images are very large, so it will a take very long on the full scale images.
