### ISSUE TITLE
No module named 'lap'

### ISSUE THREAD

**Issue by bemoregt** [yzhq97/cnn-registration#7]
Hi, @yzhq97 

I met this error when run demo.py

oem@sgi:~/cnn-registration/src$ 
oem@sgi:~/cnn-registration/src$ python3 demo.py 
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import Registration
  File "/home/oem/cnn-registration/src/Registration.py", line 10, in <module>
    from lap import lapjv
ModuleNotFoundError: No module named 'lap'
oem@sgi:~/cnn-registration/src$ 
oem@sgi:~/cnn-registration/src$ 

What's wrong with me?
I already installed pip3 install lap.
but this error happen.

Thanks in advance~

from @bemoregt.

**Comment by inrainbws** [comment]
You need to run `pip install lap`.
The "lap" package provides implementation of the Jonker-Volgenant Algorithm which solves linear assignments.

**Comment by bemoregt** [comment]
I've already installed pip install lap.
but this error happen.

**Comment by huangpan2507** [comment]
> 
> 
> I've already installed pip install lap.
> but this error happen.

I also have the same problem

**Comment by Mohamed-DL** [comment]
I've already installed pip install lap.
But this error happen.

**Comment by chenziyi1202** [comment]
> 



> I've already installed pip install lap. But this error happen.

me too

**Comment by tuaha12345** [comment]
I've already installed ----->pip install lap
But same erro happen.

**Comment by tuaha12345** [comment]
I've already installed ----->pip install lap
But same error happen.

**Comment by eimifukadaa98** [comment]
eror install lap
help me pleaseeee

**Comment by IAlexEgorov** [comment]
Me too (

**Comment by MatteoMendula** [comment]
Same here

**Comment by adarshanand67** [comment]
Same here

**Comment by nassim94** [comment]
install from source. Link : https://github.com/gatagat/lap
