### ISSUE TITLE
how to identify  correct and incorrect  points, and show by blue or yellow line?

### ISSUE THREAD

**Issue by sunbin1205** [yzhq97/cnn-registration#9]
Great code, thanks for sharing!
However, the filtering of matching feature points and the display of incorrect and correct matching points in blue and yellow respectively mentioned in the article seem to have no function definition. Could you please update this part?
Because I mainly want to use the extracted correctly matched feature points for other tasks!
I can't understand the code well enough to write the function to realize the above functions. If I can receive your share, it will be very helpful to my work. Looking forward to your reply!!
Thank you very much!!

**Comment by inrainbws** [comment]
Sorry that I can't help. The point match ground truth is manually annotated and the annotation tool is a piece of MATLAB code which I do not have access to as I have left the lab.

**Comment by chuanzhidong** [comment]
> Great code, thanks for sharing!
> However, the filtering of matching feature points and the display of incorrect and correct matching points in blue and yellow respectively mentioned in the article seem to have no function definition. Could you please update this part?
> Because I mainly want to use the extracted correctly matched feature points for other tasks!
> I can't understand the code well enough to write the function to realize the above functions. If I can receive your share, it will be very helpful to my work. Looking forward to your reply!!
> Thank you very much!!

Hi, did you work it out for the problem? The one for the keypoint matching this paper. The author didn't share the codes for the keypoint matching
